---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-app-pod
  labels:
    name: postgres-app
    author: swapnil

spec:
  containers:
    - name: mypostgress-app
      image: postgres
      env:
          - name: POSTGRES_PASSWORD
            value: admin
          - name: POSTGRES_USER
            value: myuser
          - name: POSTGRES_MYDB
            value: mydb
      ports:
         - containerPort: 5432
           hostPort: 3030
...  
