---
apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels:
    name: redis-app
    author: swapnil

spec:
  containers:
    - name: my-redis-app
      image: redis
      ports:
        - containerPort: 6379
          hostPort: 2020
...
