---
apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    author: swapnil
    name: result-app
spec:
  containers:
    - name: myresult-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
          hostPort: 1010
...
