---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:  
    type: proxi
    author: telecom
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: proxi
...

