---
apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app
    author: swapnil

spec:
  containers:
     - name: myworker-app
       image: dockersamples/examplevotingapp_worker
...
